apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphql-federation-controller.fullname" . }}
  labels:
{{ include "graphql-federation-controller.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "graphql-federation-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "graphql-federation-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          args: ["--schema-name", "{{ .Values.schemaName }}"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
            - name: ENGINE_API_KEY
              value: secret
            - name: APOLLO_PARTIAL_SCHEMA_BASE_URL
              value: http://localhost:8000/partial/
            - name: APOLLO_STORAGE_SECRET_BASE_URL
              value: http://localhost:8000/secret/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
